// app/layout.tsx
import './globals.css' // 스타일이 있다면 여기에 import

export const metadata = {
  title: '메인화면',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
