import '../styles/globals.css';
import ClientLayout from './components/ClientLayout';

export const metadata = {
  title: '메인화면',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
